// Generated by CoffeeScript 1.10.0

const request = require('request');

class Doctor {
  constructor() {
    console.log("Doctor: Hi, I'm a doctor.");
  }

  //examine
  static examine(site, callback, msg) {
    console.log("Doctor: well, I'm examing."); //@@
    const options = {
      url: site.url
    };
    let message = {};
    request.get(options, function (err, res, body) {
      if (err) {
        message = {
          "status": "error",
          "statusCode": null,
          "discription": "ERROR: \"" + site.url + "\" Connection fail."
        };
        callback(message, msg);
      } else if (res.statusCode === site.status) {
        message = {
          "status": "matched",
          "statusCode": "" + res.statusCode,
          "discription": "SUCCESS: \"" + site.url + "\" has been alive :)"
        };
        callback(message, msg);
      } else if (res.statusCode !== site.status) {
        message = {
          "status": "unmatched",
          "statusCode": "" + res.statusCode,
          "discription": "ERROR: \"" + site.url + "\" [expect]: \"" + site.status + "\", [actual]: \"" + res.statusCode + "\""
        };
        callback(message, msg);
      }
    });
  };
}

module.exports.Doctor = Doctor;
