// Generated by CoffeeScript 1.10.0
const _ = require('lodash');

class Nurse {
  constructor(robot) {
    this.robot = robot;
    this.brainKey = 'sites';
    console.log("Nurse: Hi, I'm a nurse.");
  }

  getList() {
    console.log("Nurse: I'll go get patients."); //@@
    let list, ref;
    list = (ref = this.robot.brain.get(this.brainKey)) !== null ? ref : [];
    return list;
  };

  /* Remove */
  removeSite(index) {
    let list, tmp;
    list = this.getList();

    /* エラーチェック(範囲外判定) */
    if (index > (_.size(list) - 1)) {
      return false;
    }

    /* 最後の出力に使う */
    tmp = {
      url: list[index].url,
      status: list[index].status
    };

    /* indexから1つ削除 */
    list.splice(index, 1);
    return tmp;
  };


  /* Update */
  updateSite(index, newStatus) {
    let list;
    list = this.getList();
    if (index > (_.size(list) - 1)) {
      return false;
    }
    list[index].status = newStatus;
    return true;
  };

  /* index生成 */
  searchIndex(obj, key) {
    let index, newObj;
    newObj = _.map(obj, 'url');
    index = newObj.indexOf(key);
    if (index > -1) {
      return index;
    } else {
      return false;
    }
  };

  checkConfliction(obj, key) {
    if (_.findIndex(obj, {
        url: key
      }) > -1) {
      return false;
    } else {
      return true;
    }
  };
}

module.exports.Nurse = Nurse;
